### ISSUE TITLE
SM2验签的时候始终无法验证成功呢

### ISSUE THREAD

**Issue by xiaoxiaojiang20000928** [AllenDengMs/sm2_encrypt#5]
前端正常SM2签名后传输给后端JAVA
后端JAVA验证永远失败

单独在前端签名验证可以，单独在后端签名验证也可以，但是跨端验签永远是false，请问啥原因

前端使用sm2 encrypt 小程序版
后端使用sm2 encrypt JAVA BC版

privateKey：55e0265ce2f6a4eb2fe0815958141a214813970b9c481ccec56579b42e9b7c26

publicKey：
0458ae984331bc7070429e2f0c53f07d8e19bd9504d2b7c76f894ac3c8e593a58e03f9f747060f387bb4cfb091550f35d3f9605ddefc9da48605d931ce777affd6

前端代码：
 const sign = sm2.doSignature("123", privateKey)

后端接收到sign后
boolean verified = Sm2Tool.verifySign("123", sign, publicKey);
System.out.println("verified=======>"+verified);
verified一直是false，sign前后端传输过程中未改变

**Comment by AllenDengMs** [comment]
前端签名后，返回数据的不是DER编码，导致后端解析出来的数据对应不上。
改前端代码：
let sigValueHex = sm2.doSignature(msg, privateKey,  { hash:true, der:true }) // 签名
let verifyResult = sm2.doVerifySignature(msg, sigValueHex, publicKey,  { hash:true, der:true}) // 验签结果

在js-demo文件夹里面有前端代码调用示例
