### ISSUE TITLE
iOS端的怎么适配通用呢

### ISSUE THREAD

**Issue by Mscynol** [AllenDengMs/sm2_encrypt#6]
IOS端采用 GMObjC[https://github.com/muzipiao/GMObjC](url)，好像跟java无法加解密通用，大神能否试一下

**Comment by AllenDengMs** [comment]
提供一下sm2的公钥和私钥，要加密数据、加密后的数据。我测试看看

**Comment by AllenDengMs** [comment]
后台签名验签后的结果，是DER编码，IOS端的文档也有说明怎么处理DER编码的数据

**Comment by Mscynol** [comment]
已经解决了，感谢
